services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: mcp-rag-postgres
    environment:
      POSTGRES_DB: better_chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init_better_chatbot_simple.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local